name: FartherViewDistance
version: '${version}'
main: xuan.cat.fartherviewdistance.code.ChunkIndex
api-version: 1.17
softdepend: [ PlaceholderAPI ]
authors: [ xuancat0208 ]
commands:
  viewdistance:
    usage: op
